In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# load raw data
crypto_df = pd.read_csv("../Data/raw/crypto_prices_raw.csv")
crypto_df.head()

,Date,coin,Open,High,Low,Close,Volume
0,2020-01-01,BTC,7194.892090,7254.330566,7174.944336,7200.174316,18565664997
1,2020-01-02,BTC,7202.551270,7212.155273,6935.270020,6985.470215,20802083465
2,2020-01-03,BTC,6984.428711,7413.715332,6914.996094,7344.884277,28111481032
3,2020-01-04,BTC,7345.375488,7427.385742,7309.514160,7410.656738,18444271275
4,2020-01-05,BTC,7410.451660,7544.497070,7400.535645,7411.317383,19725074095

In [3]:
crypto_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20161 entries, 0 to 20160
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    20161 non-null  object
 1   coin    20161 non-null  object
 2   Open    20161 non-null  float64
 3   High    20161 non-null  float64
 4   Low     20161 non-null  float64
 5   Close   20152 non-null  float64
 6   Volume  20161 non-null  int64
dtypes: float64(4), int64(1), object(2)
memory usage: 1.1+ MB

In [4]:
crypto_df.isna().sum()

Date      0
coin      0
Open      0
High      0
Low       0
Close     9
Volume    0
dtype: int64

In [5]:
crypto_df.duplicated().sum()

np.int64(0)

In [6]:
# convert date column to datetime
crypto_df["Date"] = pd.to_datetime(crypto_df["Date"])

In [7]:
crypto_df.dtypes

Date      datetime64[ns]
coin              object
Open             float64
High             float64
Low              float64
Close            float64
Volume             int64
dtype: object

In [8]:
# sort data
crypto_df = crypto_df.sort_values(by=["coin", "Date"]).reset_index(drop=True)
crypto_df.head()

        Date coin      Open      High       Low     Close    Volume
0 2020-01-01  ADA  0.032832  0.033813  0.032704  0.033458  22948374
1 2020-01-02  ADA  0.033474  0.033507  0.032448  0.032751  20843934
2 2020-01-03  ADA  0.032748  0.034427  0.032491  0.034180  30162644
3 2020-01-04  ADA  0.034191  0.034685  0.033872  0.034595  29535781
4 2020-01-05  ADA  0.034574  0.035356  0.034545  0.034721  21479178

In [9]:
# calculate daily returns
crypto_df["daily_return"] = crypto_df.groupby("coin")["Close"].pct_change()

/var/folders/pl/qjnl2n816kd5trwzkx1r4f9r0000gp/T/ipykernel_28412/1913755477.py:2: FutureWarning: The default fill_method='ffill' in SeriesGroupBy.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  crypto_df["daily_return"] = crypto_df.groupby("coin")["Close"].pct_change()

In [10]:
crypto_df.head(10)

,Date,coin,Open,High,Low,Close,Volume,daily_return
0,2020-01-01,ADA,0.032832,0.033813,0.032704,0.033458,22948374,NaN
1,2020-01-02,ADA,0.033474,0.033507,0.032448,0.032751,20843934,-0.021131
2,2020-01-03,ADA,0.032748,0.034427,0.032491,0.034180,30162644,0.043632
3,2020-01-04,ADA,0.034191,0.034685,0.033872,0.034595,29535781,0.012142
4,2020-01-05,ADA,0.034574,0.035356,0.034545,0.034721,21479178,0.003642
5,2020-01-06,ADA,0.034751,0.037299,0.034674,0.037272,37988444,0.073471
6,2020-01-07,ADA,0.037291,0.037807,0.036653,0.037047,51562680,-0.006037
7,2020-01-08,ADA,0.037055,0.038551,0.036015,0.036435,49193345,-0.016520
8,2020-01-09,ADA,0.036445,0.036445,0.035673,0.036359,26562776,-0.002086
9,2020-01-10,ADA,0.036335,0.036980,0.034807,0.036874,47483943,0.014164

In [11]:
# calculate cumulative returns
crypto_df["cumulative_return"] = (
    (1 + crypto_df["daily_return"])
    .groupby(crypto_df["coin"])
    .cumprod() - 1
)

In [12]:
crypto_df.head(10)

,Date,coin,Open,High,Low,Close,Volume,daily_return,cumulative_return
0,2020-01-01,ADA,0.032832,0.033813,0.032704,0.033458,22948374,NaN,NaN
1,2020-01-02,ADA,0.033474,0.033507,0.032448,0.032751,20843934,-0.021131,-0.021131
2,2020-01-03,ADA,0.032748,0.034427,0.032491,0.034180,30162644,0.043632,0.021579
3,2020-01-04,ADA,0.034191,0.034685,0.033872,0.034595,29535781,0.012142,0.033983
4,2020-01-05,ADA,0.034574,0.035356,0.034545,0.034721,21479178,0.003642,0.037749
5,2020-01-06,ADA,0.034751,0.037299,0.034674,0.037272,37988444,0.073471,0.113994
6,2020-01-07,ADA,0.037291,0.037807,0.036653,0.037047,51562680,-0.006037,0.107269
7,2020-01-08,ADA,0.037055,0.038551,0.036015,0.036435,49193345,-0.016520,0.088977
8,2020-01-09,ADA,0.036445,0.036445,0.035673,0.036359,26562776,-0.002086,0.086706
9,2020-01-10,ADA,0.036335,0.036980,0.034807,0.036874,47483943,0.014164,0.102098

In [13]:
# summary stats daily returns
crypto_df.groupby("coin")["daily_return"].describe()

,count,mean,std,min,25%,50%,75%,max
coin,,,,,,,,
ADA,2276.0,0.002274,0.052856,-0.395672,-0.024638,-0.000254,0.023749,0.713276
BNB,2276.0,0.002649,0.044199,-0.419046,-0.015236,0.001444,0.018867,0.697604
BTC,2276.0,0.001525,0.031895,-0.371695,-0.012828,0.000337,0.015135,0.187465
DOGE,2276.0,0.004564,0.099502,-0.402570,-0.024444,-0.000678,0.022041,3.555466
DOT,2044.0,0.001080,0.054527,-0.379335,-0.027481,-0.001103,0.025023,0.559877
ETH,2276.0,0.002159,0.042685,-0.423472,-0.017859,0.001017,0.021438,0.259475
LTC,2276.0,0.001193,0.045684,-0.361773,-0.020228,0.000876,0.022159,0.282016
SOL,2176.0,0.004103,0.063616,-0.422809,-0.030131,-0.000382,0.033464,0.472828
XRP,2276.0,0.002308,0.054873,-0.423340,-0.019702,0.000191,0.019765,0.730750

SABINA COMMENT: Would be keen to see each of these informations per year and look for trends - perhaps add some boxplots over time for all the cryptos :)

In [14]:
crypto_df.isna().sum()

Date                 0
coin                 0
Open                 0
High                 0
Low                  0
Close                9
Volume               0
daily_return         9
cumulative_return    9
dtype: int64

In [15]:
crypto_df.to_csv("../Data/processed/crypto_prices_processed.csv", index=False)